---
- name: "Stat {{ link.dest }}"
  ansible.builtin.stat:
    path: "{{ link.dest }}"
  register: _dot_stat

- name: "Replace copied {{ link.dest }} with a symlink"
  ansible.builtin.file:
    path: "{{ link.dest }}"
    state: absent
  when: _dot_stat.stat.exists and not _dot_stat.stat.islnk

- name: "Link {{ link.dest }}"
  ansible.builtin.file:
    src: "{{ link.src }}"
    dest: "{{ link.dest }}"
    state: link
    force: true
  when: not (ansible_check_mode and _dot_stat.stat.exists and not _dot_stat.stat.islnk)
