---
- name: "Install {{ package_label }} (Debian)"
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  become: true
  when:
    - ansible_facts.os_family == 'Debian'
    - packages | default([]) | length > 0

- name: "Install {{ package_label }} (Darwin)"
  community.general.homebrew:
    name: "{{ packages }}"
    state: present
  when:
    - ansible_facts.os_family == 'Darwin'
    - packages | default([]) | length > 0
