- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (unzip, libtool, libtool-bin, libfontconfig1-dev)
  become: true
  apt:
    name: ["xsel", "unzip", "libtool", "libtool-bin", "libfontconfig1-dev", "jq"]
  tags:
    - install
    - neovim
    - alacritty
    - obsidian
    - core

- name: Install System Packages 3 (the rest)
  become: true
  apt:
    name: ["compton", "curl", "htop", "golang", "lsof", "i3", "ccache", "python3-pip", "dconf-editor", "pavucontrol", "moreutils", "clangd", "ubuntu-mate-desktop", "fonts-firacode", "xfe", "gcc", "openjdk-8-jdk", "binutils"]
  tags:
    - install
    - core

- name: Install Clang
  become: true
  apt:
    name: ["clang", "clang-11", "clang-12", "clangd", "clangd-11", "clangd-12"]
  tags:
    - install
    - neovim
    - core

# flatpak runs applications in a sandbox (not amazing but fine), and gives us the ability to easily update sw
- name: Install flatpak
  become: true
  apt:
    name: ["flatpak"]
  tags:
    - install
    - core
    - obsidian

- name: Add flathub repository
  become: true
  ansible.builtin.shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  args:
    executable: /bin/bash
  tags:
    - install
    - core
    - obsidian

- name: Install cargo
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    . "$HOME/.cargo/env"
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ user }}"
  tags:
    - install
    - alacritty
    - core

- name: Install alacritty
  ansible.builtin.shell: cargo install alacritty
  args:
    executable: /bin/bash
  environment:
    PATH: "/home/{{ user }}/.cargo/bin:{{ ansible_env.PATH }}"
  become: yes
  become_user: "{{ user }}"
  tags:
    - install
    - alacritty
    - core

- name: Link alacritty to /usr/local/bin
  become: yes
  file:
    src: "/home/{{ user }}/.cargo/bin/alacritty"
    dest: /usr/local/bin/alacritty
    state: link
    force: yes
  tags:
    - install
    - alacritty
    - core

- name: dconf i3
  shell: dconf write /org/mate/desktop/session/required-components/windowmanager "'i3'"
  tags:
    - install
    - core

- name: dconf i3
  shell: dconf write /org/mate/desktop/background/show-desktop-icons "false"
  tags:
    - install
    - core

