---
- name: Link zshrc
  ansible.builtin.include_tasks:
    file: tasks/_link.yml
    apply:
      tags: [always]
  vars:
    link:
      src: "{{ dotfiles_dir }}/.zshrc"
      dest: "{{ home_dir }}/.zshrc"
  tags: [zsh, core, dotfiles]

- name: Link zsh_profile
  ansible.builtin.include_tasks:
    file: tasks/_link.yml
    apply:
      tags: [always]
  vars:
    link:
      src: "{{ dotfiles_dir }}/.zsh_profile"
      dest: "{{ home_dir }}/.zsh_profile"
  tags: [zsh, core, dotfiles]

- name: Link zprofile
  ansible.builtin.include_tasks:
    file: tasks/_link.yml
    apply:
      tags: [always]
  vars:
    link:
      src: "{{ dotfiles_dir }}/.zprofile"
      dest: "{{ home_dir }}/.zprofile"
  tags: [zsh, core, dotfiles]

- name: Link alacritty config
  ansible.builtin.include_tasks:
    file: tasks/_link.yml
    apply:
      tags: [always]
  vars:
    link:
      src: "{{ dotfiles_dir }}/.config/alacritty"
      dest: "{{ home_dir }}/.config/alacritty"
  tags: [alacritty, desktop, dotfiles]

- name: Link neovim config
  ansible.builtin.include_tasks:
    file: tasks/_link.yml
    apply:
      tags: [always]
  vars:
    link:
      src: "{{ dotfiles_dir }}/.config/nvim"
      dest: "{{ home_dir }}/.config/nvim"
  tags: [neovim, core, dotfiles]

- name: Link tmux config
  ansible.builtin.include_tasks:
    file: tasks/_link.yml
    apply:
      tags: [always]
  vars:
    link:
      src: "{{ dotfiles_dir }}/.tmux.conf"
      dest: "{{ home_dir }}/.tmux.conf"
  tags: [tmux, core, dotfiles]

- name: Link xprofile
  ansible.builtin.include_tasks:
    file: tasks/_link.yml
    apply:
      tags: [always]
  vars:
    link:
      src: "{{ dotfiles_dir }}/.xprofile"
      dest: "{{ home_dir }}/.xprofile"
  when: ansible_facts.os_family == 'Debian'
  tags: [desktop, i3, dotfiles]

- name: Link i3 config
  ansible.builtin.include_tasks:
    file: tasks/_link.yml
    apply:
      tags: [always]
  vars:
    link:
      src: "{{ dotfiles_dir }}/.config/i3"
      dest: "{{ home_dir }}/.config/i3"
  when: ansible_facts.os_family == 'Debian'
  tags: [desktop, i3, dotfiles]

- name: Link i3status config
  ansible.builtin.include_tasks:
    file: tasks/_link.yml
    apply:
      tags: [always]
  vars:
    link:
      src: "{{ dotfiles_dir }}/.config/i3status"
      dest: "{{ home_dir }}/.config/i3status"
  when: ansible_facts.os_family == 'Debian'
  tags: [desktop, i3, dotfiles]
