- name: Copy zsh config
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/abf/
  loop:
    - "/home/abf/code/home/dotfiles/.zshrc"
    - "/home/abf/code/home/dotfiles/.zsh_profile"
  tags:
  - zsh

- name: Copy i3 config
  ansible.builtin.copy:
    src: /home/abf/code/home/dotfiles/.config/i3
    dest: /home/abf/.config
  become_user: abf
  become: yes
  tags:
  - i3

- name: Copy alacritty config
  ansible.builtin.copy:
    src: /home/abf/code/home/dotfiles/.config/alacritty
    dest: /home/abf/.config
  become_user: abf
  become: yes
  tags:
  - alacritty

