- name: Copy zsh config
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ user }}/"
  loop:
    - "/home/{{ user }}/home/dotfiles/.zshrc"
    - "/home/{{ user }}/home/dotfiles/.zsh_profile"
  tags:
  - zsh

- name: Copy i3 config
  ansible.builtin.copy:
    src: "/home/{{ user }}/home/dotfiles/.config/i3"
    dest: "/home/{{ user }}/.config"
  become_user: "{{ user }}"
  become: yes
  tags:
  - i3

- name: Copy i3status config
  ansible.builtin.copy:
    src: "/home/{{ user }}/home/dotfiles/.config/i3status"
    dest: "/home/{{ user }}/.config"
  become_user: "{{ user }}"
  become: yes
  tags:
  - i3

- name: Copy alacritty config
  ansible.builtin.copy:
    src: "/home/{{ user }}/home/dotfiles/.config/alacritty"
    dest: "/home/{{ user }}/.config"
  become_user: "{{ user }}"
  become: yes
  tags:
  - alacritty

- name: Copy neovim config
  ansible.builtin.copy:
    src: "/home/{{ user }}/home/dotfiles/.config/nvim"
    dest: "/home/{{ user }}/.config"
  become_user: "{{ user }}"
  become: yes
  tags:
  - neovim
