- name: Clone neovim
  ansible.builtin.git:
     repo: https://github.com/neovim/neovim.git
     dest: "/home/{{ user }}/code/neovim"
     depth: 1
     version: stable
  become_user: "{{ user }}"
  become: true
  tags:
    - neovim
    - core
    - install

- name: "Install neovim deps"
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - cmake
    - gettext
    - lua5.1
    - liblua5.1-0-dev
  tags:
    - neovim
    - core
    - install

- name: Neovim Make Install
  become: true
  ansible.builtin.command: bash -c "make CMAKE_BUILD_TYPE=RelWithDebInfo && sudo make install"
  args:
    chdir: "/home/{{ user }}/code/neovim"
  tags:
    - neovim
    - core
    - install
