---
- name: Install productivity packages
  ansible.builtin.include_tasks:
    file: tasks/_packages.yml
    apply:
      tags: [always]
  vars:
    packages: "{{ productivity_packages }}"
    package_label: productivity packages

- name: Install productivity casks
  ansible.builtin.include_tasks:
    file: tasks/_casks.yml
    apply:
      tags: [always]
  vars:
    casks: "{{ productivity_casks }}"
    package_label: productivity casks
