- name: Install ZSH
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]

- name: Change shell to zsh
  shell: sudo chsh -s $(which zsh)
  become_user: {{ user }}
  become: yes
  tags: *tags_for_zsh_tasks

