services:
  home:
    build:
      context: ..
      dockerfile: ansible/Dockerfile
      args:
        user: ${HOME_USER:-${USER}}
        COMPONENTS: neovim
    image: home:latest
    container_name: home
    environment:
      DEBIAN_FRONTEND: noninteractive
      HOME_HEADLESS: "1"
    command: ["tail", "-f", "/dev/null"]
