version: '3.8'

services:
  home:
    build:
      context: .
      args:
        user: abf
    image: home:latest
    container_name: home
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: ["tail",  "-f", "/dev/null"]

