#!/usr/bin/env bash
apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y software-properties-common curl git build-essential sudo && \
    apt-add-repository -y ppa:ansible/ansible && \
    apt-get update && \
    apt-get install -y ansible && \
    apt-get clean autoclean && \
    apt-get autoremove --yes

adduser abf sudo
echo 'abf ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

sudo -u abf git clone git@github.com:brian-stanton/home.git /home/abf/code

