---
- name: Select Linux target
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Set Linux target
      ansible.builtin.set_fact:
        home_target: Debian

- ansible.builtin.import_playbook: site.yml
