- hosts: localhost
  connection: local
  vars:
    user: abf
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include_tasks: tasks/core-setup.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/productivity-tools.yml
    - include_tasks: tasks/dotfiles.yml

