- hosts: localhost
  connection: local
  vars:
    user: brian
  pre_tasks:
  - name: Install homebrew
    become: true
    shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    tags:
      - install
      - core
      - mac
  tasks:
    - include_tasks: tasks/git.yml

