---
- name: Select macOS target
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Set macOS target
      ansible.builtin.set_fact:
        home_target: Darwin

- ansible.builtin.import_playbook: site.yml
