---
- name: SSH keys
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    user: "{{ ansible_facts.user_id }}"
    home_dir: "{{ ansible_facts.user_dir }}"
  tasks:
    - ansible.builtin.import_tasks: tasks/ssh.yml
