- name: New SSH Keys
  hosts: localhost
  vars:
    user: brian
  tasks:
    - name: "Create .ssh"
      ansible.builtin.file:
        path: "/home/{{ user }}/.ssh"
        state: directory
        mode: '0755'
        owner: "{{ user }}"

    - name: generate SSH key "id_ed25519"
      community.crypto.openssh_keypair:
        path: "/home/{{ user }}/.ssh/id_ed25519"
        type: ed25519
        state: present
        force: no
        owner: "{{ user }}"

