- name: New SSH Keys
  hosts: localhost
  tasks:
    - name: "Create .ssh"
      ansible.builtin.file:
        path: "~/.ssh"
        state: directory
        mode: '0755'

    - name: generate SSH key "id_ed25519"
      community.crypto.openssh_keypair:
        path: "~/.ssh/id_ed25519"
        type: ed25519
        state: present
        force: no

